2024-09-09 14:28:36,273 ERROR: Exception on /live_matches_table [GET] [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1754, in live_matches_table
    matches_data = fetch_matches_from_first_server()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1704, in fetch_matches_from_first_server
    cached_data = load_cached_data()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1691, in load_cached_data
    if time.time() - timestamp < CACHE_EXPIRATION_TIME:
NameError: name 'CACHE_EXPIRATION_TIME' is not defined
2024-09-09 14:28:39,408 ERROR: Exception on /live_matches_table [GET] [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1754, in live_matches_table
    matches_data = fetch_matches_from_first_server()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1704, in fetch_matches_from_first_server
    cached_data = load_cached_data()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1691, in load_cached_data
    if time.time() - timestamp < CACHE_EXPIRATION_TIME:
NameError: name 'CACHE_EXPIRATION_TIME' is not defined
2024-09-09 14:28:42,516 ERROR: Exception on /live_matches_table [GET] [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1754, in live_matches_table
    matches_data = fetch_matches_from_first_server()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1704, in fetch_matches_from_first_server
    cached_data = load_cached_data()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1691, in load_cached_data
    if time.time() - timestamp < CACHE_EXPIRATION_TIME:
NameError: name 'CACHE_EXPIRATION_TIME' is not defined
2024-09-09 14:28:45,544 ERROR: Exception on /live_matches_table [GET] [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1754, in live_matches_table
    matches_data = fetch_matches_from_first_server()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1704, in fetch_matches_from_first_server
    cached_data = load_cached_data()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 1691, in load_cached_data
    if time.time() - timestamp < CACHE_EXPIRATION_TIME:
NameError: name 'CACHE_EXPIRATION_TIME' is not defined
2024-09-09 14:28:50,528 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:49]
2024-09-09 16:05:15,604 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:49]
2024-09-09 16:29:15,036 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:49]
